# Generated by Django 6.0.1 on 2026-01-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicegen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
