# Generated by Django 6.0.1 on 2026-01-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicegen', '0003_invoice_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client_address',
        ),
    ]
