# Generated by Django 6.0.1 on 2026-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicegen', '0004_remove_invoice_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True),
        ),
    ]
